flush ruleset
table inet segmentation {
  chain forward {
    type filter hook forward priority 0; policy drop;
    oifname "eth3" ct state established,related counter drop comment "FAULT-D1-finance-return-broken"
    ct state established,related counter accept comment "stateful-return"

    iifname "eth2" ip saddr != 10.61.10.0/27 counter packets 0 bytes 0 log prefix "NF_SPOOF_MGMT " drop
    iifname "eth3" ip saddr != 10.61.20.0/26 counter packets 0 bytes 0 log prefix "NF_SPOOF_FIN " drop
    iifname "eth4" ip saddr != 10.61.30.0/25 counter packets 0 bytes 0 log prefix "NF_SPOOF_ENG " drop
    iifname "eth5" ip saddr != 10.61.40.0/24 counter packets 0 bytes 0 log prefix "NF_SPOOF_USERS " drop
    iifname "eth6" ip saddr != 10.61.50.0/27 counter packets 0 bytes 0 log prefix "NF_SPOOF_SRV " drop
    iifname "eth7" ip saddr != 10.61.60.0/28 counter packets 0 bytes 0 log prefix "NF_SPOOF_DMZ " drop
    iifname "eth8" ip saddr != 10.61.70.0/24 counter packets 0 bytes 0 log prefix "NF_SPOOF_GUEST " drop

    iifname "eth2" oifname "eth3" tcp dport 22 counter accept comment "mgmt-admin-finance"
    iifname "eth3" oifname "eth6" tcp dport { 443, 5432 } counter accept comment "finance-to-payroll"
    iifname "eth4" oifname "eth6" tcp dport 443 counter accept comment "engineering-to-codesvc"
    iifname "eth5" oifname "eth6" tcp dport 443 counter accept comment "users-to-staff-portal"
    iifname "eth7" oifname "eth6" tcp dport 5432 counter accept comment "dmz-to-db"

    iifname "eth8" oifname "eth1" udp dport 53 counter accept comment "guest-dns"
    iifname "eth8" oifname "eth1" tcp dport 443 counter accept comment "guest-https"
    iifname "eth5" oifname "eth1" udp dport 53 counter accept comment "users-dns"
    iifname "eth5" oifname "eth1" tcp dport 443 counter accept comment "users-https"
    iifname "eth4" oifname "eth1" tcp dport 443 counter accept comment "engineering-pkg-repo"
    iifname "eth6" oifname "eth1" tcp dport 443 counter accept comment "servers-updates"

    iifname "eth1" oifname "eth7" tcp dport 443 counter accept comment "internet-to-dmz-web"

    counter log prefix "NF_SEGMENT_DENY " drop
  }

  chain input {
    type filter hook input priority 0; policy drop;
    ct state established,related accept
    iifname "eth2" tcp dport 22 counter accept comment "mgmt-to-gateway-ssh"
    counter log prefix "NF_INPUT_DENY " drop
  }
}
