---
core:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.11
dmz:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.7
engineering:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.4
finance:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.2
gateway:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.9
guest:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.6
management:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.3
sensor:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.5
servers:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.8
users:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.10
