---
core:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.11
dmz:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.5
engineering:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.6
finance:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.10
gateway:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.3
guest:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.4
management:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.9
sensor:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.2
servers:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.7
users:
    username: 
    password: 
    platform: linux
    hostname: 172.20.20.8
